version: '3'

services:
  mongo:
    container_name: weather-forecast-api
    restart: always
    ports:
      - 27017:27017
    image: mongo
    volumes:
      - /home/Desenvolvimento-Web/docker-volumes/weather-forecast-api/MongoDB:/data/dbc
