# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Storm Glass Weather API CI

on:
  push:
    branches: [ main ] # workflow only for this branch main
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x] # project use only this version
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2

    - name: Retrieve secret
      env: 
        STORMGLASS_API_KEY: ${{ secrets.STORMGLASS_API_KEY }}
      run: |
        STORMGLASS_API_KEY="$STORMGLASS_API_KEY"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        # yarn cache files are stored in `~/.yarn` on Linux/macOS
        path: ~/.yarn
        key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-

    - name: Install dependencies
      run: yarn

    - name: Run unit test
      run: yarn test:unit

    - name: Run functional test
      run: yarn test:functional

    - name: Start the build
      run: yarn build --if-present
