# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Storm Glass Weather API CI

on:
  push:
    branches: 
    - main 
    - master
    - production 
  pull_request:
    branches:
    - main 
    - master
    - production 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] 
        mongodb-version: ['4.0']
    steps:
    - uses: actions/checkout@v2

    - name: Retrieve secret
      env: 
        STORMGLASS_API_KEY: ${{ secrets.STORMGLASS_API_KEY }}
      run: |
        touch .env
        echo STORMGLASS_API_KEY =${{ secrets.STORMGLASS_API_KEY }} >> .env

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Run unit test
      run: yarn test:unit

    - name: Run functional test
      run: yarn test:functional

    - name: Start the build
      run: yarn build 
